---
title: "Word_Count"
output: pdf_document
---

Coronavirus disease 2019 (COVID-19) has caused the largest public health crisis, and economic disaster
of the 21st century so far According to the World Health Organisation
COVID-19 has directly resulted in 4,859,277 deaths worldwide 1 , and its impact on the global economy
has been severe  Policymakers are in urgent need of evidence-based strategies to
contain the pandemic. As Fontanet & Cauchemez  report, one critical mechanism through
which epidemics are controlled is through herd immunity. Herd immunity arises when a sufficiently
large proportion of the population achieves individual immunity to an infectious disease such that
the transmission chain of the disease is halted One method of establishing
herd immunity is through vaccination programs  Preliminary
empirical evidence shows that infection detection and vaccination strategies could be critical tools in
subduing COVID-19, for example the study by Aldila, Samiadji, Simorangkir, Khosnaw & Shahzad
 finds COVID-19 vaccines to be effective in Jakarta, Indonesia. Leaders of other countries have
also implemented vaccine programs and the World Health Organisation reports that a total of
6,364,021,792 vaccine doses have been administered globally as of 10 October 2021.
In line with the international approach, South Africa has opted to issue vaccines in addition to social
distancing and lockdown measures. The South African government has stated that it aims to have
67% of the population vaccinated by the end of 2021 . However, many
South Africans are hesitant to get the COVID vaccine; Department of Health  records that
only 25% of South Africa’s adult population has been fully vaccinated as of 11 October 2021. Burger,
Maughan-Brown, Köhler, English & Tameris compiled a report, based on data from wave 5
of the NIDS-CRAM survey, and find that that around 20% of South Africans are concerned that
COVID-19 vaccines are not safe. The report also shows that relatively few people in the sample
registered to be vaccinated within two months after registration opened. Burger, Maughan-Brown
Köhler, English & Tameris conclude that a significant portion of South Africans still have to
be convinced to take the vaccine 2 . While there are different ways to encourage vaccine uptake, such
as mandatory vaccination or lump-sum transfers, insights from behaviourial economics could provide
a more cost-effective solution: a vaccine lottery.
This essay proposes a field experiment to investigate whether a vaccine lottery could improve vac-
cination rates in South Africa. The experiment explores the effect of three different lottery types -
standard, regret and referral - on the take up of vaccines. This essay is structured as follows. Section
2 briefly reviews the relevant literature on behavioural economics and health incentives. Section 3
elaborates on the South African context. Section 4 describes the design of the experiment and outlines the three types of treatment groups. Section discusses how the treatment will be administered
and how the data will be collected. Lastly, section 6 gives a pre-analysis plan of the empirical analysis
that will be performed on the data, and the final section (7) concludes. 

Health professionals and policymakers are increasingly turning to behavioural economics to understand
how people make health decisions and how behavioural insights can be used to improve public health
outcomes . While neoclassical economics
assumes that people are perfectly rational agents, behavioural economics relaxes this assumption
and uses psychology and economic theory to create more realistic models of human decision-making
. As Khaneman and Tversky show, people are subject to certain biases and often make
use of heuristics in their decision-making process, which can lead to predictable errors in judgment
Kahneman & Tversky A large literature has developed in the field of behavioural economics to
investigate how these biases can be combated and sub-optimal choices overcome to improve welfare.Thaler & Sunstein introduced the idea of a nudge 4 as a way to guide people to make better
choices. For example, Thaler & Sunstein proposed changing the default option for organ
donation in America to opt-in as opposed to explicit consent. They found that many people who were
willing to be organ donors did not take the necessary steps, and that the registration process appeared
to deter otherwise willing donors. By changing the choice architecture to presumed consent (with an
easy opt-out option), there would be more registered donors and more lives saved.
A similar type of nudge can be applied to flu vaccines. A study conducted by Chapman, Li, Colby
& Yoon on a sample of 478 participants (split into two treatment groups of 239 each) found
that vaccination rates increased by 36% under an opt-in default than under an opt-out condition.
Madrian proposes other interventions for promoting flu vaccination, such as moving the
vaccination clinic to a central location for visibility purposes, reminding people more frequently to
get vaccinated, and encouraging people to plan the time and location they will receive their flu
vaccination. The last two nudges have been, to some extent, implemented in South Africa for the
COVID vaccine: the government has sent out SMS’s encouraging South Africans to get vaccinated,
and a self registration portal has been set up for citizens to enroll in the Electronic Vaccination Data
System (EVDS) . This portal can be seen as a type of commitment
device, in addition to being a data collection mechanism.


Behavioural economic theory and empirical studies suggest that lotteries can be a useful device for
public health interventions. A lottery system can be a cost-effective mechanism for changing behaviour
compared to direct transfers because people tend to overweight small probabilities, which is a key
insight from the work by Kahneman & Tversky on prospect theory. Due to this nonlinear
probability weighting, an individual overestimates her chances of winning a lottery. Björkman Nyqvist,
Corno, Walque & Svensson ran an experiment in Lesotho, where participants were entered into
a financial lottery and they could win a cash prize if they tested negative for sexually transmitted
infections. In spite of the fact that the lottery had low expected payments, HIV incidence decreased
by 21.4% over two years as a result of the intervention. Björkman Nyqvist, Corno, Walque & Svensson found that the lottery incentive worked particularly well at targeting participants who were
more prone to risky sexual behaviour. This supports the theory that risk-seeking individuals value
lotteries more. 

Björkman Nyqvist, Corno, Walque & Svensson  investigated the impact of a lottery intervention
on the health choices of men living with HIV in SOuth Africa. The paper found that the participants
who were eligible for the lottery started antiretroviral therapy sooner than those in the control group This provides some indication that a
vaccine lottery in South Africa could potentially be effective


Drawing further on prospect theory, the concepts of loss aversion, reference dependence and regret
avoidance can also be included in health interventions through a “regret lottery”. Kahneman & Tversky describe loss aversion as a cognitive bias whereby people experience losses as more painful than
the pleasure they receive from an equivalent gain. Thus, people are more willing to take on risk in
order to avoid a loss, and are less risk seeking when pursuing gain 
Reference dependence follows on from loss aversion and suggests that people define gains and losses
relative to a reference point People are also subject to regret
avoidance; where there is a significant emotional cost attached to regret and thus people will make
decisions to avoid regretting alternative decisions in the future  A “regret
lottery” takes advantage of these three principles by entering all participants into a lottery but the
winner can only claim the prize contingent on some condition. If this condition is not met, a new
winner is selected. By entering all participants, people’s reference point is shifted to “I have a chance
at winning the lottery”. However, if a person is not eligible to claim the prize because he does not
meet the required condition, he feels he is losing the chance to claim the prize. He is more likely to
try and meet the condition in order to minimise the pain of this loss. Additionally, he will want to
avoid the regret that would come from having missed the opportunity to claim the prize.



Several empirical papers investigate how “regret lotteries” can improve health behaviours. Humphrey,
Small, Jensen, Volpp, Asch, Zhu & Troxel analysed the effect of a daily regret lottery on cholesterol-lowering, and heart medication adherence. Every day, members of the treatment group chose a two-digit number. If a participant’s number matched at least one digit of the randomly drawn
lottery number, she was eligible to win a cash prize. However, she could only claim her winnings if she
Page 5
had taken her relevant prescribed medication the previous day. The results of the paper show that the
treatment group better adhered to their medication regime than the control group. The authors also noted that participants appeared to be engaged even after 6 months of the program. In a different study Husain, Diaz, Schwartz, Parsons, Burg, Davidson & Kronish found that implementing
a weekly regret lottery increased adherence to a
self-monitoring study protocol.


Some states in America have attempted to run regret lotteries to encourage people to get vaccinated
against COVID. An unpublished paper by Gandhi, Milkman, Ellis, Graci, Gromet, Mobarak, Butten-
heim, Duckworth, Pope, Stanford, Thaler & Volpp  evaluates the effect of weekly regret lotteries
in Philadelphia. After giving away around $400,000 in cash prizes to residents, the authors did not
find convincing evidence that the regret lotteries significantly increased first-dose vaccination rates for
the treatment groups. Although, the authors do acknowledge that there were some design flaws in
the experiment that could be clouding the results  Similarly disappointing results
were found in Ohio, where randomly selected vaccine recipients could receive up to $1 million. The
study by Walkey, Law & Bosch  found no increase in COVID vaccination rates following the
lottery incentive. To the best of my knowledge, there have been no studies on COVID-19 vaccine
lotteries in South Africa 5 - a gap which this experiment is intended to fill. This experiment would also
contribute to the empirical literature on lotteries as public health interventions and the integration of
behavioural economics into public policy.


There are currently four vaccines which have been approved by the South African Health Products
Regulatory Authority for use in South Africa: Johnson & Johnson (J&J), Pfizer, Sinovac and As-
traZeneca. The two main vaccines being rolled out in South Africa are the J&J and Pfizer, which are
both available for free. Vaccines are currently only available to individuals over the age of 18. The
J&J vaccine only requires 1 dose; and the Pfizer vaccine requires two doses, 6 weeks apart. For the
purposes of this field experiment, fully vaccinated refers to an individual who has had either 1 J&J
shot, or both shots of the Pfizer vaccine. Vaccinated refers to an individual who has had 1 shot of
either vaccine.


The sample used will be the same sample used for the Coronavirus Rapid Mobile Survey (NIDS-
CRAM). NIDS-CRAM was created in response to the pandemic as a way to build a representative
data set of the South African population to inform decision-making (Ingle, 2021). Thus far, there
have been five waves of NIDS-CRAM surveys, with wave 5 comprising a sample of 5,862 people
being surveyed during 6 April to 11 May 2021 (Ingle (2021) p.14). Wave 3 consisted of a total of
8,157 potential participants, of which 6,130 were successfully interviewed. For the purposes of this
field experiment, the 8,157 people from Wave 3 will be contacted and asked to participate in the
experiment. It seems reasonable to expect between 5,500 and 6,200 people to participate, given the
previous rates of attrition experienced in NIDS-CRAM.The
first group is the control group, where individuals will not be entered into any vaccine lottery. The
other 3 groups are will receive different lottery treatments, which are explained below. There will be
3 monthly lotteries for each treatment group, which will run simultaneously. Thus, in total there will
be 9 lotteries for this field experiment, with 3 lotteries every month. Each lottery will award a cash
prize of R1,000,000.


For the first treatment group, if an individual has received a vaccination shot 4 within a given month,
she will be entered into that month’s vaccine lottery. At the end of the month, a winner is randomly
selected from the lottery pool. Once it is verifed that the winner has been vaccinated, she will be
privately contacted and will receive a cash prize. It will then be announced via sms to everyone in
the treatment group (group 1) that the lottery has been won, the amount of the lottery prize, and the
winner’s province.
Following the approach of Gandhi, Milkman, Ellis, Graci, Gromet, Mobarak, Buttenheim, Duckworth,
Pope, Stanford, Thaler & Volpp (2021), the second lottery is a “regret lottery”. Every individual in
the sample is entered into a monthly lottery but an individual may only claim her prize if she has
been vaccinated (i.e. had at least 1 shot of any vaccine). At month end, a winner is randomly drawn
from the lottery pool. If the winner has been vaccinated, she will be privately notified and will receive
a cash prize. It will then be announced via sms to everyone in the treatment group (group 3) that the
lottery has been won, the amount of the cash prize, the winner’s province and a reminder that only
vaccinated individuals are eligible to win the lottery.
The final treatment is a “referral lottery”. An individual is entered into the monthly lottery if 2
conditions are met: he is vaccinated, and he refers a friend to get vaccinated and the friend gets
vaccinated. Both the individual from the sample and his friend are entered into the lottery. At the
end of the month, a winner is selected, verified to be vaccinated and privately informed. An SMS is
sent out to the treatment group with the same information as for group 2 and group 3, in addition to
a message thanking the sample for protecting their friends as well as a reminder that they can refer
more friends to be eligible for the following month’s lottery.